services:
  funji_db:
    image: postgres
    container_name: funji_db
    restart: always
    ports:
      - 4457:5432
    env_file:
      - .env
    volumes:
      - funji_db:/var/lib/postgresql/data

  funji_app:
    container_name: funji_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - funji_db
    env_file:
      - .env

volumes:
  funji_db:
